In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt     
import csv
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [26]:
dataset = pd.read_csv('matchesfinal.csv')
X = dataset.iloc[:,[2,4,5,6,7]]
Y = dataset.iloc[:,10]

In [27]:
print(X)

          city                        team1                        team2  \
0    Hyderabad          Sunrisers Hyderabad  Royal Challengers Bangalore   
1    Bangalore  Royal Challengers Bangalore             Delhi Daredevils   
2       Mumbai        Kolkata Knight Riders               Mumbai Indians   
3       Mohali  Royal Challengers Bangalore              Kings XI Punjab   
4       Mumbai          Sunrisers Hyderabad               Mumbai Indians   
..         ...                          ...                          ...   
559     Mumbai        Kolkata Knight Riders               Mumbai Indians   
560    Chennai          Chennai Super Kings               Mumbai Indians   
561  Hyderabad          Sunrisers Hyderabad             Delhi Daredevils   
562  Hyderabad             Delhi Daredevils          Chennai Super Kings   
563  Hyderabad               Mumbai Indians          Chennai Super Kings   

                     toss_winner toss_decision  
0    Royal Challengers Bangalore      

In [28]:
print(Y)

0              Sunrisers Hyderabad
1      Royal Challengers Bangalore
2                   Mumbai Indians
3                  Kings XI Punjab
4                   Mumbai Indians
                  ...             
559                 Mumbai Indians
560                 Mumbai Indians
561               Delhi Daredevils
562            Chennai Super Kings
563                 Mumbai Indians
Name: winner, Length: 564, dtype: object


In [29]:
l1 = LabelEncoder()
l2 = LabelEncoder()
l3 = LabelEncoder()
l4 = LabelEncoder()
l5 = LabelEncoder()
l6 = LabelEncoder()
X['city'] = l1.fit_transform(X['city'].astype(str))
X['team1'] = l2.fit_transform(X['team1'].astype(str))
X['team2'] = l3.fit_transform(X['team2'].astype(str))
X['toss_winner'] = l4.fit_transform(X['toss_winner'].astype(str))
X['toss_decision'] = l5.fit_transform(X['toss_decision'])
Y = l6.fit_transform(Y.astype(str))

C:\Users\dhira\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\dhira\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
C:\Users\dhira\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydat

In [30]:
print(X['city'].unique())
X

[ 4  0  8  7  6  3  5  1  2  9 10]


city  team1  team2  toss_winner  toss_decision
0       4      7      6            6              1
1       0      6      1            6              0
2       8      3      4            4              1
3       7      6      2            6              0
4       8      7      4            4              1
..    ...    ...    ...          ...            ...
559     8      3      4            4              1
560     1      0      4            0              0
561     4      7      1            1              1
562     4      1      0            0              1
563     4      4      0            4              0

[564 rows x 5 columns]

In [31]:
Y

array([7, 6, 4, 2, 4, 3, 4, 3, 1, 3, 7, 7, 4, 4, 3, 3, 7, 2, 7, 4, 1, 2,
       4, 3, 7, 2, 2, 4, 6, 3, 4, 3, 0, 1, 6, 3, 5, 1, 0, 5, 2, 5, 0, 7,
       2, 0, 4, 1, 2, 5, 1, 6, 2, 4, 5, 2, 7, 4, 0, 3, 5, 4, 0, 3, 5, 2,
       3, 4, 2, 1, 4, 2, 5, 4, 0, 1, 5, 2, 6, 2, 1, 5, 6, 3, 5, 0, 5, 0,
       5, 3, 4, 1, 3, 7, 1, 6, 0, 4, 6, 0, 7, 5, 6, 7, 2, 4, 6, 5, 4, 5,
       3, 1, 5, 4, 1, 4, 0, 1, 3, 6, 0, 4, 2, 1, 5, 0, 5, 3, 7, 2, 7, 6,
       2, 4, 7, 4, 0, 6, 1, 7, 4, 3, 0, 7, 3, 4, 0, 6, 0, 0, 5, 4, 3, 5,
       4, 2, 7, 3, 0, 2, 3, 7, 2, 4, 6, 1, 4, 6, 3, 5, 3, 0, 4, 3, 0, 1,
       6, 3, 4, 0, 2, 6, 0, 6, 7, 2, 2, 5, 7, 6, 4, 0, 4, 6, 0, 4, 1, 5,
       6, 0, 5, 4, 3, 1, 4, 0, 3, 1, 2, 5, 1, 5, 3, 1, 6, 0, 2, 3, 6, 4,
       1, 2, 3, 1, 4, 3, 1, 2, 0, 5, 4, 6, 3, 2, 6, 0, 4, 0, 2, 4, 0, 1,
       3, 2, 6, 7, 1, 7, 4, 3, 0, 0, 3, 3, 6, 5, 4, 7, 5, 4, 0, 6, 7, 0,
       3, 5, 2, 6, 5, 0, 7, 0, 6, 1, 0, 2, 4, 0, 3, 5, 4, 0, 5, 4, 7, 1,
       0, 3, 7, 2, 4, 6, 5, 4, 0, 5, 6, 7, 3, 5, 2,

In [32]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.3, random_state = 0)
classifier = RandomForestClassifier(n_estimators=40,criterion="gini", random_state = 42, min_samples_leaf=10, max_depth = 8)

In [33]:
classifier.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=8, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=10, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=40,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [34]:
y_pred = classifier.predict(X_test)

In [35]:
print(Y_test)
print(y_pred)

[4 6 7 0 3 0 1 4 2 3 2 7 7 0 0 4 0 6 6 2 3 3 1 5 4 1 1 2 4 6 1 0 7 6 3 6 7
 6 6 7 3 4 4 5 3 5 2 4 5 2 7 6 4 3 1 4 4 4 2 4 5 3 2 0 0 5 4 0 7 4 5 0 0 5
 4 3 4 2 7 0 3 3 7 2 7 0 5 4 0 3 0 4 3 2 6 0 0 8 1 4 8 0 7 0 0 0 7 6 2 5 1
 4 4 6 2 0 4 2 3 2 0 1 4 7 5 6 3 1 2 4 0 3 7 3 5 1 0 3 2 3 5 4 4 3 4 4 6 6
 3 1 3 0 5 3 4 5 4 4 5 5 4 5 5 7 6 1 3 0 7 3]
[4 6 7 0 3 0 1 4 1 4 2 7 7 0 0 4 0 2 6 2 1 6 1 2 2 7 3 2 0 0 1 0 7 0 7 4 7
 7 4 3 4 4 4 5 3 5 7 3 7 2 0 6 4 3 1 4 4 6 2 7 5 3 2 0 0 1 7 0 7 0 5 5 0 6
 3 3 4 6 0 0 3 0 7 1 4 7 1 4 0 3 0 4 3 2 1 0 0 5 1 4 6 0 3 0 0 0 7 2 1 5 2
 4 4 6 2 7 2 2 3 2 0 7 4 7 3 6 3 1 1 0 0 3 7 3 0 1 0 3 2 3 5 4 3 4 4 4 5 6
 3 0 3 0 5 7 3 5 1 3 1 0 4 7 5 7 6 1 3 0 7 3]


In [36]:
print(np.sum(Y_test==y_pred))

108


In [37]:
X['toss_decision'].unique()

array([1, 0], dtype=int64)

In [38]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'poly', degree = 4, random_state = 0, gamma='auto')
classifier.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=4, gamma='auto', kernel='poly',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [39]:
y_pred = classifier.predict(X_test)

In [40]:
y_pred

array([4, 6, 7, 0, 3, 0, 6, 4, 2, 4, 2, 5, 5, 0, 6, 4, 0, 2, 6, 2, 1, 6,
       6, 5, 4, 7, 3, 4, 4, 0, 1, 0, 7, 6, 3, 4, 7, 6, 6, 3, 7, 4, 4, 1,
       3, 4, 7, 3, 5, 2, 7, 6, 4, 3, 2, 7, 4, 4, 2, 4, 1, 3, 2, 0, 0, 1,
       7, 0, 7, 0, 5, 5, 0, 6, 3, 3, 4, 6, 0, 0, 5, 0, 7, 1, 7, 7, 1, 4,
       0, 2, 0, 4, 3, 2, 6, 0, 0, 5, 1, 4, 6, 0, 7, 0, 0, 0, 3, 2, 2, 2,
       1, 2, 7, 1, 6, 0, 2, 5, 3, 2, 0, 7, 7, 7, 5, 6, 3, 1, 1, 0, 0, 3,
       7, 2, 1, 1, 0, 5, 2, 3, 3, 4, 3, 3, 4, 4, 5, 6, 3, 0, 3, 0, 5, 3,
       3, 3, 1, 3, 5, 5, 4, 6, 3, 7, 6, 1, 3, 0, 7, 3])

In [41]:
Y_test

array([4, 6, 7, 0, 3, 0, 1, 4, 2, 3, 2, 7, 7, 0, 0, 4, 0, 6, 6, 2, 3, 3,
       1, 5, 4, 1, 1, 2, 4, 6, 1, 0, 7, 6, 3, 6, 7, 6, 6, 7, 3, 4, 4, 5,
       3, 5, 2, 4, 5, 2, 7, 6, 4, 3, 1, 4, 4, 4, 2, 4, 5, 3, 2, 0, 0, 5,
       4, 0, 7, 4, 5, 0, 0, 5, 4, 3, 4, 2, 7, 0, 3, 3, 7, 2, 7, 0, 5, 4,
       0, 3, 0, 4, 3, 2, 6, 0, 0, 8, 1, 4, 8, 0, 7, 0, 0, 0, 7, 6, 2, 5,
       1, 4, 4, 6, 2, 0, 4, 2, 3, 2, 0, 1, 4, 7, 5, 6, 3, 1, 2, 4, 0, 3,
       7, 3, 5, 1, 0, 3, 2, 3, 5, 4, 4, 3, 4, 4, 6, 6, 3, 1, 3, 0, 5, 3,
       4, 5, 4, 4, 5, 5, 4, 5, 5, 7, 6, 1, 3, 0, 7, 3])

In [42]:
np.sum(Y_test==y_pred)

105